"""add document storage metadata

Revision ID: 3891eb62b645
Revises: b0fab498c80f
Create Date: 2026-09-12 16:23:23.573437

"""
from typing import Sequence, Union

from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision: str = '3891eb62b645'
down_revision: Union[str, Sequence[str], None] = 'b0fab498c80f'
branch_labels: Union[str, Sequence[str], None] = None
depends_on: Union[str, Sequence[str], None] = None


def upgrade() -> None:
    """Upgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.add_column('documents', sa.Column('storage_key', sa.String(length=1024), nullable=True))
    op.add_column('documents', sa.Column('file_size', sa.Integer(), nullable=True))
    op.add_column('documents', sa.Column('content_type', sa.String(length=255), nullable=True))
    # ### end Alembic commands ###


def downgrade() -> None:
    """Downgrade schema."""
    # ### commands auto generated by Alembic - please adjust! ###
    op.drop_column('documents', 'content_type')
    op.drop_column('documents', 'file_size')
    op.drop_column('documents', 'storage_key')
    # ### end Alembic commands ###
